### PR TITLE
Gems and some tiny fixes

### PR DESCRIPTION
**Pull request by segfaultdev**
- Added 6 different types of gems(not 7 like in the game as it considers amber to be a gem which is just stupid)
- Made glass placeable
- Added edible items
- Added pots that drop random items from loot tables
- Show item names on hotbar
- Fixed jungle flooding issues
- Added surface caves(I still don't feel like they are ok, might change it later)
- Added two new workspaces: The loom and the sawmill(both 2x2, unlike in Terraria where they are bigger)
- Added cobwebs and silk
- Added working beds
- Fixed vulture generation
- Made cursor more visible

### CODE REVIEW

**Comment by KBD2** [comment]
I'll probably just make the beds craftable with wood only for now, so that it's easier for players to obtain. I'd like to add cobwebs at the same time as cave surface entrances, right now it's kind of hard to find a good cave.

**Comment by segfaultdev** [comment]
Well I just added basic surface cave entrances, and I'm going to add cobwebs, as now entering caves is a bit easier, if you are ok with that.

**Comment by DamieFC** [comment]
Amber is too a gem!

**Comment by segfaultdev** [comment]
> Amber is too a gem!

Thanks for your extensive and complete feedback, but we are sorry to tell you that no, amber is not a gem, nor it was or it will ever be one.

**Comment by KBD2** [comment]
You should probably use the map tool for any non-minor world generation changes, as otherwise it's harder to find any issues with said changes.

**Comment by segfaultdev** [comment]
Ok, I'll add it when I have some time, then I'll polish some stuff and it'll be ready to be merged

**Comment by segfaultdev** [comment]
Ok, I think it's ready to be merged, I fixed some stuff and solved some conflicts on your latest commits and it's all done (:

**Pull request merged**
