### PR TITLE
Jungle, ores, tools and more!

### PR DESCRIPTION
**Pull request by segfaultdev**
Oh hey! I saw your amazing project, and I decided to help a bit by adding some stuff! Sorry if my code is a bit shitty, I've tried sticking to your style as much as possible. Hope you like it (:

Things added:
- Jungle biome
- Mud and clay(now distinguishable from dirt) blocks
- Copper and tin ores
- Tin armor and tools
- Saving player position on save
- Title messages!
- Tools and armor prefixes(broken, powerful, keen, godly, damaged, etc.)
- Copper, silver, gold and platinum coins
- Demonic eyes and lenses
- Cactus item, tools and armor
- Zombie arms

### CODE REVIEW

**Comment by KBD2** [comment]
This is looking really good so far, thanks for taking the time to do this! I'll have a look into the inventory crash you're describing, though I haven't been able to reproduce it on your latest commit so far.

**Comment by segfaultdev** [comment]
Glad you liked it! I'm actually not able to reproduce the crash that I told you about after the jungle commit, but I was able to before it, so maybe it fixed itself magically (:

I also updated some of the textures, and I'm going to work on tool stats for variety like in the original game.

**Comment by segfaultdev** [comment]
Hi again! I finally finished the jungle biome, and added a lot of tool prefixes that affect the player's attack, defense and pick's power. I also increased the version so old saved games without player positions and updated items don't generate corruptions.

Finally, I remade the splash screen with a better one, and added my name on it, hope you don't mind that last thing, and you can always remove it if you don't like it (:

**Comment by KBD2** [comment]
I was actually planning on putting you in the credits - if you don't mind I'll see if I can tweak a few things in the PR (when you're all finished with it) before I merge it, just leave a comment when you're all done.

**Comment by segfaultdev** [comment]
Ok, I have some ideas of things to add next, but I'll leave it like this for now, so you can start doing whatever tweaks you want to (:

**Comment by segfaultdev** [comment]
Tried playing the game for a bit, and I found the inventory crash, again! Sometimes it doesn't crash, but only freezes for 5-10 seconds. I'll try figuring it out later, but maybe you can help with that too.

**Comment by KBD2** [comment]
Feel free to make another PR if you want to add some more content! I'm planning on adding beds, bows, and the Merchant before the next release, but I'll be happy with anything else you want to implement as well.

**Comment by segfaultdev** [comment]
Ok, thanks for merging! By the way, I changed the generation step names because I thought they look better with funnier names, but I see you prefer the regular ones (:

**Comment by segfaultdev** [comment]
Also, I was actually thinking of adding bows, what a coincidence! But hey, as it's your project and I have little to no idea of how to make the arrows work, I'll let you do it along with that and I'll work on other stuff I have planned like more ores (:

**Pull request merged**
